package org.DDAN.GDCC.GDC;

public enum TokenType {
	LEFT_PAREN, RIGHT_PAREN, RIGHT_BRACE, LEFT_BRACE, DOT, SEMICOLON,
	PLUS_PLUS, MINUS_MINUS,
	PLUS, MINUS, STAR, SLASH,
	LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, EQUAL_EQUAL, BANG_EQUAL,
	AND, OR, BANG,
	EQUAL, PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL,
	HASH,
	COMMA,
	IDENTIFIER, INT_LITERAL,
	BREAK, CASE, CONST, CONTINUE, DEFAULT, DO, ELSE, ENUM, FOR, IF, INT, RETURN, SIZEOF, STRUCT, SWITCH, TYPEDEF, UNION, VOID, WHILE, STATIC, BOOL, TRUE, FALSE,
	EOF
}
